# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: leifcr-mongrations 0.1.6 ruby lib

Gem::Specification.new do |s|
  s.name = "leifcr-mongrations"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jonbell", "leifcr"]
  s.date = "2013-10-28"
  s.description = "Mongrations aims to be similar to ActiveRecord's data migrations, except\ninstead of worrying about schema changes, offering a way to change data when\nnecessary"
  s.email = "leifcr@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "generators/mongrations/templates/mongration.rb",
    "generators/mongrations_generator.rb",
    "init.rb",
    "install.rb",
    "lib/mongrations.rb",
    "lib/mongrations/exceptions.rb",
    "lib/mongrations/migration_proxy.rb",
    "lib/mongrations/migrator.rb",
    "lib/mongrations/mongration.rb",
    "lib/mongrations/railtie.rb",
    "lib/mongrations/schema_migration.rb",
    "tasks/mongo.rake",
    "test/mongrations_test.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/leifcr/mongrations"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.4"
  s.summary = "Data migrating for MongoMapper"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo_mapper>, [">= 0.12.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.8"])
    else
      s.add_dependency(%q<mongo_mapper>, [">= 0.12.0"])
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
    end
  else
    s.add_dependency(%q<mongo_mapper>, [">= 0.12.0"])
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.8"])
  end
end

